server {
    listen 3550;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location /zgroup_genset/ {
        try_files $uri $uri/ /zgroup_genset/index.html;
    }

    location = /zgroup_genset {
        return 301 /zgroup_genset/;
    }

    location / {
        return 301 /zgroup_genset/;
    }
}
